### ISSUE TITLE
Can't fetch history log; missing job ID

### ISSUE THREAD

**Issue by 2803media** [commoncrawl/cc-mrjob#13]
Hi I try the example on EMR and now it give the following error

```
Looking for step log in s3://mrjob-441a54771bdd7c0f/tmp/logs/j-2WHDDYZ8NRNET/steps/s-1I1JKZ4Y1T9J7...
Looking for step log in s3://mrjob-441a54771bdd7c0f/tmp/logs/j-2WHDDYZ8NRNET/steps/s-1I1JKZ4Y1T9J7...
Can't fetch history log; missing job ID
No counters found
```

Any idea? Bug or bad configuration?

**Comment by sebastian-nagel** [comment]
Did the job fail? Or is it only a problem of parsing log files to extract counters and errors?

**Comment by sebastian-nagel** [comment]
Ev. this is because the cluster is terminated before the history logs are fetched. Of course, you could modify the configuration so that no cluster is launched, launch the cluster "by hand" and start the job from the master node instead.
In case, you've missed it: there's a Spark-based alternative to cc-mrjob, see [cc-pyspark](//github.com/commoncrawl/cc-pyspark). But cc-mrjob is still supported and at Common Crawl we keep using it.

**Comment by 2803media** [comment]
Thanks sebastian I'll look in this direction (with mrjob)
Best and thanks for the job with common crawl!
